apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  namespace: flux-system 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app
          image: ghcr.io/hejweather/hejweatherapp:2f0c175fcbba2b31de2f82fc817211a4eddc8296
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"