apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  namespace: flux-system 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app
          image: ghcr.io/hejweather/hejweatherapp:dc980ba35a0373c3a397da4f6096b07d64d9030f
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"