apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app # Name of the deployment
  namespace: default # valfritt namn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app # Label to match with the pod
  template:
    metadata:
      labels:
        app: weather-app # Label to match with the selector
    spec:
      containers:
        - name: weather-app # Name of the container
          image: ghcr.io/hejweather/hejweatherapp:2617105056e119a5b627a557923050b1b593a75a # Image to be used
          imagePullPolicy: IfNotPresent # Pull policy
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"