apiVersion: v1
kind: Service
metadata:
  name: weather-app
  namespace: weather-app
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: weather-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP