apiVersion: v1
kind: Service
metadata:
  name: weather-app
  namespace: flux-system
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30840
  selector:
    app: weather-app