name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'  # Adjusted to your app's directory
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: hejweather
          password: ${{ secrets.GH_TOKEN }}

      # Build and push the Docker image
      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/hejweather/hejweatherapp:${{ github.sha }} .
          docker push ghcr.io/hejweather/hejweatherapp:${{ github.sha }}