name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'  
      - 'cluster/**'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: hejweather
          password: ${{ secrets.GH_TOKEN }}

      # Build and push the Docker image
      - name: Build and Push Docker image
        run: |
          docker build --no-cache \
            --build-arg REACT_APP_WEATHER_API_KEY=${{ secrets.REACT_APP_WEATHER_API_KEY }} \
            --build-arg REACT_APP_IPSTACK_KEY=${{ secrets.REACT_APP_IPSTACK_KEY }} \
            --build-arg REACT_APP_CHATGPT_API_KEY=${{ secrets.REACT_APP_CHATGPT_API_KEY }} \
            -t ghcr.io/hejweather/hejweatherapp:${{ github.sha }} .
            
            

          docker push ghcr.io/hejweather/hejweatherapp:${{ github.sha }}
          
          
      
      - name: Update deployment
        run: |
          sed -i "s|ghcr.io/hejweather/hejweatherapp:.*|ghcr.io/hejweather/hejweatherapp:${{ github.sha }}|" cluster/aks/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add cluster/aks/deployment.yaml
          git commit -m "Update deployment image to ${{ github.sha }}"
          git push
